name: 'configuration_management'

services:

  play:
    image: ovski/ansible:v2.13.3
    volumes:
      - ./:/var/www/ansible
      - ./hosts:/etc/ansible/hosts
      - ${SSH_KEY}:/root/.ssh/id_rsa
      - ${DOCKER_CERTS}:/var/www/ansible/docker_certs
    command: >
      ansible-playbook /var/www/ansible/main.yml
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    profiles: [ansible]
