version: '3.7'

services:

  play:
    image: ovski/ansible:v2.13.3
    volumes:
      - ./:/var/www/ansible
      - ./hosts:/etc/ansible/hosts
      - ~/.ssh/id_rsa_manager:/root/.ssh/id_rsa_manager
      - ~/.ssh/id_rsa_worker:/root/.ssh/id_rsa_worker
      - /home/user/.docker/manager_certs:/home/user/.docker/manager_certs
    command: >
      ansible-playbook /var/www/ansible/main.yml
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
    profiles: [ansible]

  semaphore:
    ports:
      - 80:3000
    image: public.ecr.aws/semaphore/pro/server:v2.16.18
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: P@ssword123
      SEMAPHORE_ADMIN_NAME: Baptiste
      SEMAPHORE_ADMIN_EMAIL: baptiste.bouchereau@gmail.com
      ANSIBLE_HOST_KEY_CHECKING: "False"
    volumes:
      - ./semaphore_volume/data:/var/lib/semaphore
      - ./semaphore_volume/config:/etc/semaphore
      - ./semaphore_volume/tmp:/tmp/semaphore
