---
- name: Update servers and setup docker swarm managers
  hosts: swarm_managers
  roles:
    - up_to_date
    - swarm_manager

- name: Update servers and setup docker swarm workers
  hosts: swarm_workers
  roles:
    - up_to_date
    - swarm_worker

- name: Setup backup servers
  hosts: backup_servers
  roles:
    - borgbackup
