- name: Make sure python3-docker is present
  apt:
    name: python3-docker
    state: present
    update_cache: yes

- name: Init a new swarm
  docker_swarm:
    state: present

- name: Retrieve the swarm worker token
  shell: docker swarm join-token -q worker
  register: swarm_worker_token
  changed_when: False

- debug:
    msg: "Worker token : {{ swarm_worker_token['stdout'] }}"
  when: not ansible_check_mode
