- name: Make sure python3-docker is present
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: true

- name: Init a new swarm
  community.docker.docker_swarm:
    state: present

- name: Retrieve the swarm worker token
  ansible.builtin.command: docker swarm join-token -q worker
  register: swarm_manager_worker_token
  changed_when: false

- name: Show swarm worker token
  ansible.builtin.debug:
    msg: "Worker token : {{ swarm_manager_worker_token['stdout'] }}"
  when: not ansible_check_mode
