- name: Assert mandatory variables are defined
  ansible.builtin.assert:
    that:
      - docker_cert_passphrase is defined
      - docker_data_root is defined
      - client_cert_folder_path is defined

- name: Create the daemon.json file
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart docker

- name: Ensure /var/docker exists
  ansible.builtin.file:
    path: /var/docker
    state: directory
    mode: '0755'

- name: Move a script to generate certificates
  ansible.builtin.template:
    src: create_certs.sh.j2
    dest: /var/docker/create_certs.sh
    mode: 'u+x'

- name: Check if certificates already exists
  ansible.builtin.stat:
    path: /var/docker/cert.pem
  register: remote_docker_daemon_certificates_file

- name: Check if certificates are expired
  ansible.builtin.command: openssl x509 -checkend 86400 -noout -in /var/docker/cert.pem
  register: remote_docker_daemon_certificates_expired
  when: remote_docker_daemon_certificates_file.stat.exists
  changed_when: false
  failed_when: >
    (remote_docker_daemon_certificates_expired.rc != 0 and remote_docker_daemon_certificates_expired.rc != 1) or
    (remote_docker_daemon_certificates_expired.rc == 1 and remote_docker_daemon_certificates_expired.stdout != 'Certificate will expire')

- name: Delete expired certificates
  ansible.builtin.file:
    path: /var/docker/{{ item }}
    state: absent
  with_items:
    - ca.pem
    - cert.pem
    - key.pem
    - ca.srl
    - ca-key.pem
    - server-cert.pem
    - server-key.pem
  when: remote_docker_daemon_certificates_expired.rc == 1 and remote_docker_daemon_certificates_expired.stdout == 'Certificate will expire'

- name: Generate the certificates
  ansible.builtin.command: /var/docker/create_certs.sh
  args:
    creates: /var/docker/ca.pem
  notify: Restart docker

- name: Ensure the folder to store client certs exists
  ansible.builtin.file:
    path: "{{ client_cert_folder_path }}"
    state: directory
    mode: '0700'
  delegate_to: 127.0.0.1
  run_once: true

- name: Retrieve the client certificates
  ansible.builtin.fetch:
    src: "/var/docker/{{ item }}"
    dest: "{{ client_cert_folder_path }}/{{ item }}"
    flat: true
  run_once: true
  with_items:
    - ca.pem
    - cert.pem
    - key.pem

- name: Ensure docker listen on tcp port 4444
  community.general.ini_file:
    path: /lib/systemd/system/docker.service
    section: Service
    option: ExecStart
    value: /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock  -H tcp://0.0.0.0:4444
    mode: '644'
  notify: Restart docker

- name: Restart docker if necessary
  ansible.builtin.meta: flush_handlers
