- name: The user 'backup_user' is present
  user:
    name: backup_user
    shell: /bin/bash
    generate_ssh_key: yes

- name: The borgbackup dependencies are present
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - libssl-dev
      - openssl
      - libacl1-dev
      - libacl1
      - build-essential
      - libfuse-dev
      - fuse3
      - pkg-config

- name: The borgbackup package is present
  apt:
    name: borgbackup

- name: The borg repository folder is present
  file:
    path: /home/backup_user/borg_repositories
    state: directory
  become: yes
  become_method: su
  become_user: backup_user
