- name: The aptitude package is present
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - aptitude

- name: Pip packages are present
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv

- name: The packages are updated and upgraded
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true
    autoremove: true
    autoclean: true
  notify:
    - List updated packages

- name: Check if the file /var/run/reboot-required is present
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: up_to_date_reboot_required
  changed_when: false

- name: Reboot machine if needed
  ansible.builtin.reboot:
  when: up_to_date_reboot_required.stat.exists and not skip_reboot|default(false)
