- name: The aptitude package is present
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - aptitude

- name: Pip packages are present
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - python
      - python-pip
      - python3
      - python3-dev
      - python3-pip
      - python-virtualenv

- name: The packages are updated and upgraded
  apt:
    upgrade: safe
    update_cache: yes
    autoremove: yes
    autoclean: yes
