- name: Assert mandatory variables are defined
  ansible.builtin.assert:
    that:
      - swarm_manager_addr is defined

- name: Make sure python3-docker is present
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: true

- name: The worker node is joined to the manager
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[groups.swarm_managers[0]].swarm_manager_worker_token.stdout }}"
    advertise_addr: "{{ swarm_manager_addr }}"
    remote_addrs:
      - "{{ swarm_manager_addr }}"
