- name: Assert mandatory variables are defined
  assert:
    that:
      - swarm_manager_token is defined
      - swarm_manager_addr is defined

- name: Make sure docker-pip is present
  pip:
    name: docker

- name: The worker node is joined to the manager
  docker_swarm:
    state: join
    join_token: "{{ swarm_manager_token }}"
    advertise_addr: "{{ swarm_manager_addr }}"
    remote_addrs:
      - "{{ swarm_manager_addr }}"
